- name: Install Podman on Debian
  hosts: debian_servers
  become: yes
  tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - software-properties-common
          - uidmap
        state: present

    - name: Add Podman backports repository (Debian 12 or newer)
      ansible.builtin.apt_repository:
        repo: "deb http://deb.debian.org/debian bookworm-backports main"
        state: present
        filename: "bookworm-backports"
      when: ansible_distribution_release == "bookworm"

    - name: Install Podman from backports
      apt:
        name: podman
        state: present
        default_release: "{{ ansible_distribution_release }}-backports"
