- name: Install .NET 9 SDK and Runtime on Debian
  hosts: debian_servers
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Add Microsoft package signing key
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add Microsoft package repository for Debian 12 (bookworm)
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/debian/12/prod bookworm main"
        filename: "microsoft-prod"
        state: present

    - name: Update apt cache after adding repo
      apt:
        update_cache: yes

    - name: Install .NET 9 SDK and Runtime
      apt:
        name:
          - dotnet-sdk-9.0
          - dotnet-runtime-9.0
        state: present
